name: GitHub Ações Exemplo

on: 
  push:  # Aciona a execução quando há um push no repositório

jobs:
  explore-github-actions:
    runs-on: ubuntu-latest

    steps:
      - name: Exibir informações do evento
        run: |
          echo "O trabalho foi automaticamente acionado por um evento: ${{ github.event_name }}"
          echo "Este trabalho agora está sendo executado em um servidor: ${{ runner.os }}"
          echo "O nome da sua filial é ${{ github.ref }} e seu repositório é ${{ github.repository }}"

      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Exibir informações sobre o repositório
        run: |
          echo "O repositório ${{ github.repository }} foi clonado para o runner."
          echo "O fluxo de trabalho agora está pronto para testar seu código no runner."

      - name: Listar arquivos no repositório
        run: ls ${{ github.workspace }}

      - name: Mostrar status do job
        run: echo "O status deste trabalho é ${{ job.status }}"
